### ISSUE TITLE
Instructions Fail

### ISSUE THREAD

**Issue by bibleuspro** [Noesis/UE4Plugin#2] opened 2016-10-19 07:34 UTC
I have also left a comment:
https://github.com/Noesis/UE4Plugin/pull/1#issuecomment-254691352

which leads to my forum pics.

I have done further testing, and plugin work trying to break through the unreal learning curve and now I am fairly convinced there is something wrong with the setup process.

Firstly it looks like this plugin is for Engine 4.10?
https://github.com/Noesis/UE4Plugin/blob/master/NoesisGUI.uplugin
"EngineVersion" : "4.10.0"

I recommend putting that limitation on the readme. As I tried everything from GitHub source to 4.11-13 before I arrived at 4.10.

There does seem to be a typo, which may be preventing the module from being found.

*\NoesisGUI-SDK1.3\Include\NoesisGUI.h
NoesisGUI.uplugin

but everywhere else it is NoesisGui (lowercase)

I can verify now that after following the instructions very carefully, I still get this error with the capitalization typo showing everytime.
![fail](https://cloud.githubusercontent.com/assets/19825051/19509364/a19571ac-959b-11e6-8d46-6b82637054f6.PNG)

I will admit, I did have to figure out that I was supposed to be putting this in the engine plugins folder found in the engines downloaded from the launcher, and not in the GitHub source.

At this point I really don't have much else to go on. The other similar problems I had with other plugins were resolved when I switched to the launcher versions of these engines, so now it is only this plugin that has me at a loss and the only thing I can think is the typo? Or something messed up with latest noesis native sdk.

**Comment by bibleuspro** [comment] 2016-10-19 07:56
Might also be a typo here:
https://github.com/Noesis/UE4Plugin/blob/master/NoesisGUI.uplugin#L26

uneeded comma ]**,**

**Comment by Hayaweh** [comment] 2016-10-19 08:33
"Firstly it looks like this plugin is for Engine 4.10?"
- No, it does mean that the minimum version required to use the plugin is 4.10 :) 

"Might also be a typo here:
https://github.com/Noesis/UE4Plugin/blob/master/NoesisGUI.uplugin#L26

uneeded comma ],"
- The comma is necessary since the comma applies to the "Module" field. 

I don't see any typo with the plugin name and there has been no changes there since I managed to get it working as well. :/  ( I confirmed that there as been no code change to the plugin descriptor files by browsing the repo..

How did you name the folder you put the plugin in? 
NoesisGUI or NoesisGui?

**Comment by bibleuspro** [comment] 2016-10-19 08:47
I have tried both.
When I rename NoesisGUI.uplugin to NoesisGui.uplugin it looks like this.
![no-caps](https://cloud.githubusercontent.com/assets/19825051/19511680/734c7584-95a5-11e6-8a2e-790a77217067.PNG)

When I change folder to NoesisGUI and edit the plugin name to:
"Name" : "NoesisGUI",

it will look like this:
![caps](https://cloud.githubusercontent.com/assets/19825051/19511731/b70ae0b2-95a5-11e6-8d14-231544857dda.PNG)

As a sanity check, is there something I need to do when setting up the plugin, like some commonly known thing that is not in the readme. Like do I need to open it in VS and build it or something? I also noticed the shaders look like they were built in VS 2010 and 12? I don't have those on this machine, trying to keep the bloat down. Not sure if that matters.

One thing that I saw that made me think I might not be doing something you are is you mentioned the intermediate folder:
https://github.com/Noesis/UE4Plugin/pull/1#issue-181429423
_SDK, Binaries and Intermediate! :)_ 

I don't see an Intermediate in this repo.

**Comment by bibleuspro** [comment] 2016-10-19 08:57
Like is there a way to see better errors/debug info than just "failed to load"? It is giving us very little to go on.

For example, I saw here http://www.noesisengine.com/forums/viewtopic.php?p=5261#p5261

> Which version of UE4 did you use?
> It does not seem to work with 4.13 **(crashes in UE4Editor-Shaders.dll it seems)** 
> 
> Can you confirm me that you worked with another version?
> 
> EDIT 15:25: I created a pull-request with some .gitignore additions for those working with the git repo in place in their UE4 project folder and also **fixed some errors that started popping up from the NoesisGui.Build.cs**, which was trying to copy to a non-existing folder! 

How did you see the errors/logs for the shaders.dll and build.cs errors for instance, seems I may be missing something here to help me debug this issue. Thanks again.

**Comment by Hayaweh** [comment] 2016-10-19 09:09
My debug/errors were different since it was crashing at editor launch, wat after plugins detection, it was completely unrelated and due to my putting the plugin in game plugins and not engine. :) 

For the Intermediate folder, it's unrelated as well.
Intermediate folder, in UE4 is the folder where all temporary/local files are stored that are related to building etc. It's basically files that are machine-specific and that you do not want to push on the repository because they are "yours only". 

I am seeing that you are trying with 4.10, can you confirm me that you get the same issue with 4.13?

**Comment by bibleuspro** [comment] 2016-10-19 09:45
Thanks for your help. BTW.

Ok I just tried with 4.13.1 again, and no luck. Please take a peak on the forms again, one of your questions triggered a new thought that is likely the problem:

> Also, please let me note that in the case you put it in an existing engine version, you should only be required to start the project and it should prompt you to compile the new NoesisGui module of which it did not find the compiled dlls yet. 
http://www.noesisengine.com/forums/viewtopic.php?p=5313#p5313

This is exactly my problem I think, I can't get it to ask me to compile, what do you see? I only get this when I try this new method (detailed on forum post)
![hmm](https://cloud.githubusercontent.com/assets/19825051/19513812/89dd649e-95ae-11e6-8b45-b6c6549d79d3.PNG)

**Comment by Hayaweh** [comment] 2016-10-19 09:47
If it's not finding the proper module, this is normal.
It is in fact proof that it is entering the "module-check" phase, where it checks for all the plugins dlls etc. 

I will take a look at the forum post and come back to you if I get any idea.

**Comment by bibleuspro** [comment] 2016-10-19 09:57
thanks.
btw here is my folder structure, hopefully it matches yours.
![folders](https://cloud.githubusercontent.com/assets/19825051/19514249/1bf797fe-95b0-11e6-82f6-71f46496f21e.PNG)

**Comment by Hayaweh** [comment] 2016-10-19 10:20
Yep, similar hierarchy here.

I've also been able, after doing a bit of renaming to make things more clear.... THAT. It's a specific module causing issue (understand the various folders in the /Source folder)

Basically, it does not seem to find the NoesisGui.Build.cs located at Source/NoesisGui/
Which, makes no sense, since it's here. 

It also mean that the caps between the plugin and module in your screenshots is just normal. :) 

I am still investigating. I will let you know if I find anything.

**Comment by bibleuspro** [comment] 2016-10-19 20:52
Glad I am not totally insane.

**Comment by hcpizzi** [comment] 2016-10-20 08:17
Hi guys,

Sorry for the late reply.

I've tested the plugin against the head of the release branch from Epic's depot as of a week ago. 4.10 is the minimum version.

In your latest screen capture I see that you don't have a Binaries folder under Engine/Plugins/NoesisGui. There are no precompiled binaries in this distribution, the plugin needs to be built. I take it you may be using the pre built version, instead of building it from the sources in GitHub?

**Comment by bibleuspro** [comment] 2016-10-20 09:49
http://www.noesisengine.com/forums/viewtopic.php?p=5327#p5327

> hcpizzi wrote:
> It looks to me like what you're trying to build is NoesisGUI itself, not the UE4 plugin (you seem to have the sources in Engine/Plugins/NoesisGui/Source/ThirdParty/Noesis/NoesisGUI-SDK1.3/Src, which is not part of the precompiled distribution package).

Sorry I am brand new to the processes over here. I downloaded the .zip from the beta forum. What else am I to do? Sounds like I need to compile it and then put the compiled version into the unreal plugin? Note: These steps are not on readme.
How do I get the precompiled distribution package and what does that folder structure look like?
2Extract the Noesis GUI SDK into Engine/Plugins/NoesisGui/Source/ThirdParty/Noesis
I am new to the beta, I have the NoesisGUI-NativeSDK-1.3.0b2.zip, from the NoesisGUI 1.3 BETA2 forum thread. Is this all I need? Are there build instructions somewhere to get the binaries?

> "In your latest screen capture I see that you don't have a Binaries folder under Engine/Plugins/NoesisGui"

_Where are the instructions for building the plugin? I agree this is an issue._ 

> "I take it you may be using the pre built version, instead of building it from the sources in GitHub?"

I have tried both. Errors below.


> As I replied in the GitHub issue thread, at the moment the plugin is distributed in source only form. You need to build UE4 from the source so it builds the plugin. The third step (regenerate the unreal solution and projects) is part of UE4's build instructions from GitHub.

I am getting confused here, above you had mentioned "NoesisGUI-SDK1.3/Src, which is not part of the precompiled distribution package)." and I am being told I need to build Unreal from source. This is what I am trying to do. Am I to build both the binaries from NoesisGui first, then rebuild the engine from source? I am getting confused what exactly I am to build, when to place binaries and how I am to organize the files.

To me NoesisGUI-NativeSDK-1.3.0b2.zip is the SDK? I take it that is a wrong assumption, and the real SDK in reference is the compiled version of this zip, which I haven't figured out how to properly build yet. I am sure this is trivial though at this point. (compared to all the other hoops so far  )

Instructions: (GitHub)
**1Copy the contents of this repository into Engine/Plugins/NoesisGui.
2Extract the Noesis GUI SDK into Engine/Plugins/NoesisGui/Source/ThirdParty/Noesis.
3Regenerate the UE4 projects.**

Above are the only instructions. I have tried following these 3 steps on both the GitHub source and then Epic Launcher versions of the engine which also come with their own source. And I get the same error all the time.

> "I can commit precompiled binaries and add setup instructions both..."

Absolutely, I can see you might be trying to keep the readme small so it looks easy but honestly please be verbose there seems to be some assumptions of steps being made that I am missing. And others will too. Or do both, create a wiki with more details for those lost like me 

Here is what I get when I try to build from source, though it sounds like the problem is I don't have the sdk binaries setup right. I got lost "Extract the Noesis GUI SDK into Engine/Plugins/NoesisGui/Source/ThirdParty/Noesis" here. Unclear what the folder structure of the sdk means as I am new and this workflow is new.

Screenshots of failed epic GitHub build attempt and project refresh?
![source](https://cloud.githubusercontent.com/assets/19825051/19554416/b70d2518-9675-11e6-8e23-81c67fec6a8f.PNG)
![bat](https://cloud.githubusercontent.com/assets/19825051/19554422/bce6f3c4-9675-11e6-8587-1c772c2fdeb7.PNG)
![meta](https://cloud.githubusercontent.com/assets/19825051/19554427/c07586c2-9675-11e6-860f-c3c88c7e7bd8.PNG)

**Comment by hcpizzi** [comment] 2016-10-20 10:46
I've replied in the forums. I'll copy my response here for completeness:

> Sorry, I'll try to be more precise.

> There are two parts to the plugin. The first part is the NoesisSDK itself. This is the part that step 2 refers to. You don't need to build this from the sources, and the integration may not work with versions other than the beta 2 you downloaded from the forums. From your screen captures I can see that part looks fine and everything is where it should be.

> The second part is the UE4 plugin. This consist of two modules, and this is the part that needs to be built from the sources provided in the GitHub repository. That's what step 3 refers to. In the root folder of your UE4 GitHub checkout there should be a batch file named GenerateProjectFiles.bat. I can see you've ran it, because you have UE4.sln. If you run it after having installed the plugin, and open and build the UE4 project that should build the plugin. Here's what confuses me, because building the plugin causes the copy of NoesisGui.usf to Engine/Shaders, and I can see you have the file there, but no Binaries folder in Engine/Plugins/NoesisGui.

> The main reason why it's got to be an Engine plugin at the moment is the shader. Unfortunately at the moment UE4 doesn't support loading shaders from anywhere but Engine/Shaders. If I managed to get around this restriction the plugin could be installed anywhere, but so far i haven't been able to find a workaround.

**Comment by bibleuspro** [comment] 2016-10-20 10:58
Thanks, I have suggested a pull request for the readme.
https://github.com/Noesis/UE4Plugin/pull/3

I think the extra folders just throws things for a loop, once I deleted them and only left the 3 key ones Bin, Include and Lib needed for all CPP integration from what I understand. This was the key piece of info I did not have. The magic button if you will. Feel free to close this issue out. But I do recommend a wiki or something be put up first, to help others that might fail at instructions like me.

Thanks for the nudges, I got there and I just creating my first blueprint. Now off to bed. Cheers.

**Comment by Hayaweh** [comment] 2016-10-20 11:10
Good call on only keeping Bin/Lib/Includes folders from the SDK. I also kept Doc.. Because that can always come in handy. 
Good job. (It's a path length issue, too long)
Goodnight!

**Comment by bibleuspro** [comment] 2016-10-24 17:32
Feel free to close this issue out.

**Comment by hcpizzi** [comment] 2016-10-26 10:17
Closing :)

**Closed by hcpizzi** 2016-10-26 10:17 UTC
